-- SQL Script to update the fertilization table in Supabase
-- Run this in the Supabase SQL Editor to ensure all columns exist

-- 1. Create table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.fertilization_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_labor DATE NOT NULL,
    año INT,
    mes TEXT,
    zona TEXT,
    hacienda TEXT,
    suerte TEXT,
    motor TEXT,
    metrica TEXT,
    clasificacion TEXT,
    valor DECIMAL,
    area_ste DECIMAL,
    area_aplicada DECIMAL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Add missing columns individually if they don't exist
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='fertilization_data' AND column_name='hac_ste') THEN
        ALTER TABLE public.fertilization_data ADD COLUMN hac_ste TEXT;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='fertilization_data' AND column_name='tipo') THEN
        ALTER TABLE public.fertilization_data ADD COLUMN tipo TEXT;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='fertilization_data' AND column_name='fecha_recomendacion') THEN
        ALTER TABLE public.fertilization_data ADD COLUMN fecha_recomendacion DATE;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='fertilization_data' AND column_name='unidades') THEN
        ALTER TABLE public.fertilization_data ADD COLUMN unidades DECIMAL;
    END IF;
END $$;

-- 3. Indexing for performance
CREATE INDEX IF NOT EXISTS idx_fecha ON public.fertilization_data (fecha_labor);
CREATE INDEX IF NOT EXISTS idx_zona_hacienda ON public.fertilization_data (zona, hacienda);
CREATE INDEX IF NOT EXISTS idx_motor ON public.fertilization_data (motor);
